### ISSUE TITLE
Show buttons by default

### ISSUE THREAD

**Issue by gabeodess** [carrot/share-button#136]
It would be nice if there was a configuration option to show the buttons by default as opposed to having to push the "share" button in order to reveal them.

**Comment by jenius** [comment]
This is a massive change in the design of the project. The whole point of the button is to compact the shares and delay the loading of all that stuff until a person actually wants to share. If you don't need to click the button, why have a button in the first place, right? So now that the button has been stripped out, it's just a row of customizable share icons, which is a different project.

You are welcome to do this if you'd like, but it would be better as a fork than an option in this project, since the button is the entire point :grinning: Thank you for the feedback though, and still very much open to discussion even though I am going to close this issue.

**Comment by gabeodess** [comment]
I see, I hadn't considered that the buttons aren't actually loaded until someone clicks the "share" button.  That's smart.  I wouldn't imagine it would be that hard to automatically trigger that event (and some other css) on pageload based on a configuration though, right?

The concern I think a lot of people might have is that the share button requires an additional click than if the network buttons were shown directly.

I could imagine people wanting the "share" button on certain pages for the efficiency boost, but then wanting to have the network buttons visible by default as well on specific pages they are trying to promote without having to include another share-button library.

**Comment by jenius** [comment]
Yeah, I see what you are saying for sure. But the entire point of this project is to have it require an additional click. Our general view on this is that if people want to share your page, they will do so, and we trade an additional click for the following benefits: 

- If you have a button that says "SHARE" in clear capital letters, it seems counter-intuitive to me that someone would like your content enough to share it, intend to share it by clicking that button, then once they see the networks go "Shit I have to click again? This is way too much work, fuck it" and not share the page.
- A bunch of share buttons on a page is spammy-looking and visually distracting. Compressing them into a button frees up visual real estate on your page and makes it look more elegant and less spammy.
- When you hide the networks behind a button, you can load the page much quicker, as mentioned previously, and load less of the networks' tracking scripts and other bullshit without the user intending for that to happen.

These are totally opinions backed by zero research at all. If someone did research on this, it would be awesome, I'd be interested to see the result. But with all that being said, using this library is a trade-off -- one some people are willing to make and others are not. For those who are not, they typically choose not to use this library. But we are, which is why we made and use it.

**Comment by gabeodess** [comment]
Actually, after reviewing the plugin, I think I can accomplish what I'm talking about using the API with share.open() and some custom CSS.

Maybe I'll run an optimizely A/B test on that and see which gets more clicks.

**Comment by jenius** [comment]
Sure -- would definitely be interested to see the result! There are certainly plenty of factors that should be taken into account in such a test, but even a rough measure would be interesting.

**Comment by simonoff** [comment]
Added possibility to remove 'Share' button and not hiding buttons after click on one of them in #150
