### ISSUE TITLE
Multiple Shares on one page - only last instance is actually showing the networks on click of the button

### ISSUE THREAD

**Issue by cocovan** [carrot/share-button#186]
I have a list of items laid out in a Bootstrap grid. For each one, I want to have a share button so I'm creating a new Share for each item passing in the ID of the empty div. The Share buttons are created and on click, I do see the active class being added and removed and the correct calls, but the flyout never appears, apart from the final one.

I've created a fiddle showing the issue - https://jsfiddle.net/f7e6udmz/

While I'm here, even though pinterest is set to false, it still shows. However, if I edit the Share source JS and set the default of pinterest to false, it works and the pinterest icon is never shown. Let me know if you want me to raise a separate issue for that one.

**Comment by hhsnopek** [comment]
Hey @cocovan - Here's the updated jsfiddle: https://jsfiddle.net/a4wq79ev/1/

I spotted a couple problems, but the share-button is working in your jsfiddle. Within your config object you are listing the networks outside of the `networks object`, which causes share-button to not apply those. Also your grid that you're using is hiding the share-buttons, because of overflow. In my fiddle I have changed the flyout to `top right` so you can see them all working.

**Comment by cocovan** [comment]
@hhsnopek - thanks, Henry. What a numpty I am with the config object thing. Sorry about that. 

And nice spot with the overflow - I was wondering if it was CSS that was causing me the difficulties.

Thanks again and it's a lovely wee bit of code this.

**Comment by hhsnopek** [comment]
no problem! :)
