### ISSUE TITLE
[Styles] I cannot see all box

### ISSUE THREAD

**Issue by Chrysweel** [carrot/share-button#238]
Hello. 

I want use this library, but I found an error with styles by default. Somebody can help me ?

I use Bootstrap and I have two columns
```
<div class="col-xs-12 col-sm-3">
```
And on the left, I dont see the box of pinterest, twitter and facebook.

![share-button](https://cloud.githubusercontent.com/assets/1416870/10487773/f30221ea-7295-11e5-8fc1-66126ae488cf.png)
![share-button-div](https://cloud.githubusercontent.com/assets/1416870/10487778/f6324dcc-7295-11e5-8a8a-e3c1c9ab7e09.png)

This should be within the column of Bootstrap... any solution ? 

thanks in advance !

**Comment by hhsnopek** [comment]
This would be due to Bootstrap, I would first make sure you're using the latest release of share-button (1.0.2). Then once you've done that you'll want to reset the `line-height` of the parent to `share-button` to be `1em1 so that the export icon is vertically centered. To fix the overflow you can do a couple things, depending on the width of the screen and container you could have the networks display: `top right` or `middle right`. Otherwise you'll want to set the `z-index` of `share-button` to be greater than the parent (container) element
