### ISSUE TITLE
what if i want to use `button` tag?

### ISSUE THREAD

**Issue by safareli** [carrot/share-button#245]
what if i want to use a `button` tag instead of `share-button` what can i do?

**Comment by hhsnopek** [comment]
You are able to use a class and pass the class name as the first argument into the share button. Just wondering, why don't you want to use the share-button element?



--
Henry Snopek

**Comment by hhsnopek** [comment]
Also because you're not using the share-button element you'll have to modify the style sheet as it looks for that element rather than a class



--
Henry Snopek

**Comment by safareli** [comment]
I think better way would be to apply styles using class selector like `.share-button` or whatever and on javascript side don't use that tag  just select elements with class selector like `.js-share-button`. for example I wanted to use it on div element because i was using React and couldn't accomplish my coule without editing this library. or what if someone wants to use button element for accessibility reasons for example?

**Comment by hhsnopek** [comment]
With react you should still be able to use a [custom element](http://addyosmani.com/blog/component-interop-with-react-and-custom-elements/). Otherwise regarding accessibility, I believe any custom element is recognized as a div. You can use a class as specified before, just change `share-button` in the stylus file to `.you-custom-class`.

**Comment by safareli** [comment]
you cant use div element and just path selector because of this line 
https://github.com/carrot/share-button/blob/v1.0.2/src/share-button.js#L165

and you cant path some specific dom node because it will think that it's a configuration object
https://github.com/carrot/share-button/blob/v1.0.2/src/share-button.js#L19

 think there should be way to:
  - pass dom node as an element to `ShareButton`
  - use any html element with some predefined class and


to accomplish these tasks I needed to change css and js :/

**Comment by hhsnopek** [comment]
Oh yeah, totally forgot we did that. You're correct we don't allow just class/div's anymore because a custom tag is less complex. Excuse myself from earlier, didn't have my :coffee: yet. Otherwise @declandewet helped me out with his react knowledge and created an [example](http://codepen.io/declandewet/pen/xwzZWE) which uses the latest release.

**Comment by safareli** [comment]
I'm using it on server and it doesn't works as expected https://gist.github.com/safareli/5e2a99b2fec9420ca608

But the point is that one should be able to
  - pass dom node as an element to `ShareButton`
  - use any html element with some predefined class and
  - use custom html in share button (in case someone wants to use some other icon or multiple icons for example and or whatever)

that you think about these points?

**Comment by hhsnopek** [comment]
I'm unfortunately unable to debug the provided code without having the client side code as well. I'm not familiar enough with your code to fully debug it. If you provide more code I can dig further into the issue though.

Alright to touch on your points:
> pass dom node as an element to ShareButton
> use any html element with some predefined class

No longer needed because Custom Tags have been available since HTML 4 and act like standard `div` when styling. With more recent technology, like Web components, you can now __render__ [x-tags](http://www.html5rocks.com/en/tutorials/webcomponents/customelements/) in javascript. With that in mind, share-button is __not__ a web component because browser support. With that in mind, you're able to create custom elements with react or web components. Because share-button isn't a web component, all you need to do when you display `share-button` is to instantiate `new ShareButton(opts)`.

> use custom html in share button (in case someone wants to use some other icon or multiple icons for example and or whatever)

In share-button we create all the icons in our [styles file](https://github.com/carrot/share-button/blob/master/src/share-button.styl). This full customization of the button without having to touch any html. We no longer use the Entypo font icon set because we can render all of the icons as background images.

**Comment by safareli** [comment]
ok whatever
