### ISSUE TITLE
How to nest share button properly in Bootstrap menu?

### ISSUE THREAD

**Issue by brylie** [carrot/share-button#276]
We have a site navigation bar built using Bootstrap 3. When adding the `<share-button>` element to the Bootstrap menu, the `Share` text is mis-aligned with other navigation links. Inspecting the page shows that the hidden social icons are pushing the `Share` text out of alignment:

![screenshot-1](https://cloud.githubusercontent.com/assets/17307/12845975/690183ce-cc12-11e5-9103-309ba4e41e10.png)

What CSS rules should I apply, so that the share button aligns with other Bootstrap navigation menu links (pictured)?

**Comment by brylie** [comment]
I found one solution for this question, was to create a parent container and set `padding-top`:

```css
#share-button-container {
  padding-top: 1.7em;
}
```

However, I am not sure if there is a better solution, so would appreciate feedback.

**Comment by virre** [comment]
The problem is based on the fact that all other elemnts in the menu is a-elements and the general placement and styleing have been done on a elements. Basiclly if we want to align things inside the menu as the setup now we either need to add it as a or make some special edits to make sure the element inherits and uses the same styleing. Also the glyph-icon styleing inside the a in spans might create missmatches with how the text is generated here. 

Just from the first glance this seems to be the issue. I am going to try to style the li element you used to match the a elements used elsewhere.

**Comment by virre** [comment]
To clearify: 

"What CSS rules should I apply, so that the share button aligns with other Bootstrap navigation menu links (pictured)?"

As it current is it needs to be an <a> element that inherits from the navbar elements. 

It might be possible to style the share-button-container the same way

**Comment by hhsnopek** [comment]
Hey @brylie the share-button was really meant, by default, to be used with spacing around/below a block of text. Your solution is perfect :smile:
