### ISSUE TITLE
Not working with latest version

### ISSUE THREAD

**Issue by gauravmak** [carrot/share-button#282]
Hello, am I making any mistake in this fiddle?
https://jsfiddle.net/0f0hetvg/1/

Why is it not working? I want to test share-button on a custom element actually.

**Comment by hhsnopek** [comment]
Hey @gauravmak oddly I'm unable to get it to work inside jsfiddle or codepen - though I went ahead and pulled down `v1.0.3` and locally got [examples/animation.html](examples/animation.html) to work

**Comment by gauravmak** [comment]
Surprisingly, its working locally when js and css files are also in local environment. If we include direct links to the files, same problem happens. So, codepen/jsfiddle isn't the reason for sure.

**Comment by hhsnopek** [comment]
are you downloading the files directly from the latest release?

**Comment by gauravmak** [comment]
Yes.

**Comment by hhsnopek** [comment]
let me give it another go, one sec

**Comment by hhsnopek** [comment]
I went ahead and downloaded it locally again and created a fresh html file and loaded everything in. Everything is working as it should, which browser & os are you using?

**Comment by gauravmak** [comment]
I said its not working when direct links are references i.e. 
https://github.com/carrot/share-button/releases/download/v1.0.3/share-button.min.css
and
https://github.com/carrot/share-button/releases/download/v1.0.3/share-button.js

When files are downloaded locally, its dine :)

**Comment by hhsnopek** [comment]
Ohhh, sorry about that - completely missed what you were saying! But that would be correct it doesn't work as it should because it's coming from github
> see http://stackoverflow.com/questions/9841026/reference-github-file-in-jsfiddle

you'll need to reference the raw files here: https://github.com/carrot/share-button-bower/releases. This still might not work considering Github is not a CDN, we previously had these served on a CDN. I'm uploading the previous versions of share-button tonight if you need those a well!

I'll go ahead and create an issue to add share-button to cdnjs

**Comment by gauravmak** [comment]
I see. Thank you.
In fact, my issue is different. I can't add share button to custom element.
When I googled the topic, there were some working examples but with `new Share()` instead of `new ShareButton()`.
To open an issue with an example I went to jsFiddle actually. But, made a mistake of wrong links.

**Comment by hhsnopek** [comment]
Ahh well as of now with the latest version you'll use `new ShareButton(config);` instead of `new Share()` - are you able to get it working now?

**Comment by gauravmak** [comment]
Yes, I know that and its working but only with `<share-button></share-button>`. I want it for something like `<div class="btn share-button"></div>`

**Comment by hhsnopek** [comment]
Ahh okay, I see where you're trying to go with it now - what you can do is pass the element to `
```
var element = document.getElemenstByClassName('share-button')[0];
var sharebtn = new ShareButton(element, conf);`

**Comment by hhsnopek** [comment]
Sorry I was mistaken, just pass:
`"div.btn.share-button"` instead of  `var element = document.getElementsByClassName('share-button')[0];`

I just realized my mistake, sorry about that - you'll be able to grab your element using selectors - [mdn reference](https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelectorAll)

**Comment by gauravmak** [comment]
Not working. You mean this, right?
`<button class="btn share-button"><span class="glyphicon glyphicon-share-alt"></span> Share</button>`
and
```
var el = document.querySelector("div.btn.share-button");
var share = new ShareButton(el, config);
```

**Comment by gauravmak** [comment]
Can you please guide @hhsnopek ?

**Comment by hhsnopek** [comment]
@gauravmak I hate to apologize once more, but since `share-button` `v1.0.0` we no long use any divs. The reason behind this is to be modular and use a custom element which is supported all the way back into html 4.1 (if I'm recalling correctly). [https://jsfiddle.net/r80akxrr](https://jsfiddle.net/r80akxrr) here's a jsfiddle with working resources to sharebutton's lib

**Comment by wraithseeker** [comment]
I had this issue earlier on when trying to install it but I realised I had forgotten to use document.ready to wait for the page to load before running the share func
